/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerStatus = IDL.Variant({
  'active' : IDL.Null,
  'oneLoss' : IDL.Null,
  'eliminated' : IDL.Null,
});
export const Player = IDL.Record({
  'id' : IDL.Text,
  'status' : PlayerStatus,
  'name' : IDL.Text,
  'losses' : IDL.Nat,
  'eliminated' : IDL.Bool,
  'tournamentId' : IDL.Text,
});
export const TournamentStatus = IDL.Variant({
  'active' : IDL.Null,
  'registration' : IDL.Null,
  'completed' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Text,
  'status' : TournamentStatus,
  'eliminationCount' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'winner' : IDL.Opt(IDL.Text),
});
export const MatchResult = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Match = IDL.Record({
  'id' : IDL.Text,
  'player1Id' : IDL.Text,
  'player2Id' : IDL.Text,
  'result' : MatchResult,
  'winnerId' : IDL.Opt(IDL.Text),
  'loserId' : IDL.Opt(IDL.Text),
  'player2Name' : IDL.Text,
  'byePlayerId' : IDL.Opt(IDL.Text),
  'roundNumber' : IDL.Nat,
  'tournamentId' : IDL.Text,
  'player1Name' : IDL.Text,
});
export const Round = IDL.Record({
  'completed' : IDL.Bool,
  'matches' : IDL.Vec(Match),
  'roundNumber' : IDL.Nat,
  'tournamentId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPlayer' : IDL.Func([IDL.Text, IDL.Text], [Player], []),
  'completeTournament' : IDL.Func([IDL.Text, IDL.Text], [Tournament], []),
  'createNextRound' : IDL.Func([IDL.Text], [Round], []),
  'createTournament' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [Tournament], []),
  'deleteTournament' : IDL.Func([IDL.Text], [], []),
  'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getCurrentRound' : IDL.Func([IDL.Text], [IDL.Opt(Round)], ['query']),
  'getPlayersByTournament' : IDL.Func([IDL.Text], [IDL.Vec(Player)], ['query']),
  'getRoundsByTournament' : IDL.Func([IDL.Text], [IDL.Vec(Round)], ['query']),
  'getTournament' : IDL.Func([IDL.Text], [Tournament], ['query']),
  'recordMatchResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Match], []),
  'reshuffleCurrentRound' : IDL.Func([IDL.Text], [Round], []),
  'startTournament' : IDL.Func([IDL.Text], [Tournament], []),
  'undoMatchResult' : IDL.Func([IDL.Text], [Match], []),
  'updateTournamentStatus' : IDL.Func(
      [IDL.Text, TournamentStatus],
      [Tournament],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerStatus = IDL.Variant({
    'active' : IDL.Null,
    'oneLoss' : IDL.Null,
    'eliminated' : IDL.Null,
  });
  const Player = IDL.Record({
    'id' : IDL.Text,
    'status' : PlayerStatus,
    'name' : IDL.Text,
    'losses' : IDL.Nat,
    'eliminated' : IDL.Bool,
    'tournamentId' : IDL.Text,
  });
  const TournamentStatus = IDL.Variant({
    'active' : IDL.Null,
    'registration' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Text,
    'status' : TournamentStatus,
    'eliminationCount' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'winner' : IDL.Opt(IDL.Text),
  });
  const MatchResult = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Match = IDL.Record({
    'id' : IDL.Text,
    'player1Id' : IDL.Text,
    'player2Id' : IDL.Text,
    'result' : MatchResult,
    'winnerId' : IDL.Opt(IDL.Text),
    'loserId' : IDL.Opt(IDL.Text),
    'player2Name' : IDL.Text,
    'byePlayerId' : IDL.Opt(IDL.Text),
    'roundNumber' : IDL.Nat,
    'tournamentId' : IDL.Text,
    'player1Name' : IDL.Text,
  });
  const Round = IDL.Record({
    'completed' : IDL.Bool,
    'matches' : IDL.Vec(Match),
    'roundNumber' : IDL.Nat,
    'tournamentId' : IDL.Text,
  });
  
  return IDL.Service({
    'addPlayer' : IDL.Func([IDL.Text, IDL.Text], [Player], []),
    'completeTournament' : IDL.Func([IDL.Text, IDL.Text], [Tournament], []),
    'createNextRound' : IDL.Func([IDL.Text], [Round], []),
    'createTournament' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat)],
        [Tournament],
        [],
      ),
    'deleteTournament' : IDL.Func([IDL.Text], [], []),
    'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getCurrentRound' : IDL.Func([IDL.Text], [IDL.Opt(Round)], ['query']),
    'getPlayersByTournament' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Player)],
        ['query'],
      ),
    'getRoundsByTournament' : IDL.Func([IDL.Text], [IDL.Vec(Round)], ['query']),
    'getTournament' : IDL.Func([IDL.Text], [Tournament], ['query']),
    'recordMatchResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Match], []),
    'reshuffleCurrentRound' : IDL.Func([IDL.Text], [Round], []),
    'startTournament' : IDL.Func([IDL.Text], [Tournament], []),
    'undoMatchResult' : IDL.Func([IDL.Text], [Match], []),
    'updateTournamentStatus' : IDL.Func(
        [IDL.Text, TournamentStatus],
        [Tournament],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };