/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Match {
  'id' : string,
  'player1Id' : string,
  'player2Id' : string,
  'result' : MatchResult,
  'winnerId' : [] | [string],
  'loserId' : [] | [string],
  'player2Name' : string,
  'byePlayerId' : [] | [string],
  'roundNumber' : bigint,
  'tournamentId' : string,
  'player1Name' : string,
}
export type MatchResult = { 'pending' : null } |
  { 'completed' : null };
export interface NotificationSettings {
  'nextRoundEnabled' : boolean,
  'tournamentStartEnabled' : boolean,
  'matchResultEnabled' : boolean,
}
export interface NotificationView {
  'id' : string,
  'title' : string,
  'notifType' : string,
  'body' : string,
  'createdAt' : bigint,
  'targetPlayerName' : [] | [string],
  'tournamentId' : string,
  'readByPlayerNames' : Array<string>,
}
export interface Player {
  'id' : string,
  'status' : PlayerStatus,
  'name' : string,
  'wins' : bigint,
  'losses' : bigint,
  'eliminated' : boolean,
  'rating' : bigint,
  'disqualified' : boolean,
  'tournamentId' : string,
}
export type PlayerStatus = { 'active' : null } |
  { 'oneLoss' : null } |
  { 'eliminated' : null };
export interface Round {
  'completed' : boolean,
  'matches' : Array<Match>,
  'roundNumber' : bigint,
  'tournamentId' : string,
}
export interface Tournament {
  'id' : string,
  'status' : TournamentStatus,
  'eliminationCount' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'winner' : [] | [string],
}
export type TournamentStatus = { 'active' : null } |
  { 'registration' : null } |
  { 'completed' : null };
export interface _SERVICE {
  'addPlayer' : ActorMethod<[string, string], Player>,
  'broadcastNotification' : ActorMethod<[string, string, string], undefined>,
  'changePlayerName' : ActorMethod<[string, string], Player>,
  'changePlayerRating' : ActorMethod<[string, bigint], Player>,
  'completeTournament' : ActorMethod<[string, string], Tournament>,
  'createNextRound' : ActorMethod<[string], Round>,
  'createTournament' : ActorMethod<[string, [] | [bigint]], Tournament>,
  'deletePlayer' : ActorMethod<[string], undefined>,
  'deleteTournament' : ActorMethod<[string], undefined>,
  'disqualifyPlayer' : ActorMethod<[string], undefined>,
  'getAllTournaments' : ActorMethod<[], Array<Tournament>>,
  'getCurrentRound' : ActorMethod<[string], [] | [Round]>,
  'getNotificationLog' : ActorMethod<[string], Array<NotificationView>>,
  'getNotificationSettings' : ActorMethod<[string], NotificationSettings>,
  'getNotificationsForPlayer' : ActorMethod<
    [string, string],
    Array<NotificationView>
  >,
  'getPlayersByTournament' : ActorMethod<[string], Array<Player>>,
  'getRoundsByTournament' : ActorMethod<[string], Array<Round>>,
  'getTournament' : ActorMethod<[string], Tournament>,
  'markNotificationsRead' : ActorMethod<
    [string, string, Array<string>],
    undefined
  >,
  'recordMatchResult' : ActorMethod<[string, string, string], Match>,
  'reshuffleCurrentRound' : ActorMethod<[string], Round>,
  'startTournament' : ActorMethod<[string], Tournament>,
  'undoMatchResult' : ActorMethod<[string], Match>,
  'updateNotificationSettings' : ActorMethod<
    [string, boolean, boolean, boolean],
    undefined
  >,
  'updateTournamentStatus' : ActorMethod<
    [string, TournamentStatus],
    Tournament
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];