/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: string;
    status: PlayerStatus;
    name: string;
    losses: bigint;
    eliminated: boolean;
    tournamentId: string;
}
export interface Tournament {
    id: string;
    status: TournamentStatus;
    name: string;
    createdAt: bigint;
    winner?: string;
}
export interface Round {
    completed: boolean;
    matches: Array<Match>;
    roundNumber: bigint;
    tournamentId: string;
}
export interface Match {
    id: string;
    player1Id: string;
    player2Id: string;
    result: MatchResult;
    winnerId?: string;
    loserId?: string;
    player2Name: string;
    byePlayerId?: string;
    roundNumber: bigint;
    tournamentId: string;
    player1Name: string;
}
export enum MatchResult {
    pending = "pending",
    completed = "completed"
}
export enum PlayerStatus {
    active = "active",
    oneLoss = "oneLoss",
    eliminated = "eliminated"
}
export enum TournamentStatus {
    active = "active",
    registration = "registration",
    completed = "completed"
}
export interface backendInterface {
    addPlayer(tournamentId: string, name: string): Promise<Player>;
    completeTournament(tournamentId: string, winner: string): Promise<Tournament>;
    createTournament(name: string): Promise<Tournament>;
    deleteTournament(tournamentId: string): Promise<void>;
    getAllTournaments(): Promise<Array<Tournament>>;
    getCurrentRound(tournamentId: string): Promise<Round | null>;
    getPlayersByTournament(tournamentId: string): Promise<Array<Player>>;
    getRoundsByTournament(tournamentId: string): Promise<Array<Round>>;
    getTournament(id: string): Promise<Tournament>;
    recordMatchResult(matchId: string, winnerId: string, loserId: string): Promise<Match>;
    startTournament(tournamentId: string): Promise<Tournament>;
    updateTournamentStatus(tournamentId: string, status: TournamentStatus): Promise<Tournament>;
}
import type { Match as _Match, MatchResult as _MatchResult, Player as _Player, PlayerStatus as _PlayerStatus, Round as _Round, Tournament as _Tournament, TournamentStatus as _TournamentStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPlayer(arg0: string, arg1: string): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0, arg1);
                return from_candid_Player_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0, arg1);
            return from_candid_Player_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeTournament(arg0: string, arg1: string): Promise<Tournament> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTournament(arg0, arg1);
                return from_candid_Tournament_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTournament(arg0, arg1);
            return from_candid_Tournament_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTournament(arg0: string): Promise<Tournament> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0);
                return from_candid_Tournament_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0);
            return from_candid_Tournament_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTournament(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTournament(arg0);
            return result;
        }
    }
    async getAllTournaments(): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTournaments();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTournaments();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentRound(arg0: string): Promise<Round | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentRound(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentRound(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayersByTournament(arg0: string): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersByTournament(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersByTournament(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoundsByTournament(arg0: string): Promise<Array<Round>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoundsByTournament(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoundsByTournament(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournament(arg0: string): Promise<Tournament> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournament(arg0);
                return from_candid_Tournament_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournament(arg0);
            return from_candid_Tournament_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordMatchResult(arg0: string, arg1: string, arg2: string): Promise<Match> {
        if (this.processError) {
            try {
                const result = await this.actor.recordMatchResult(arg0, arg1, arg2);
                return from_candid_Match_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordMatchResult(arg0, arg1, arg2);
            return from_candid_Match_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async startTournament(arg0: string): Promise<Tournament> {
        if (this.processError) {
            try {
                const result = await this.actor.startTournament(arg0);
                return from_candid_Tournament_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTournament(arg0);
            return from_candid_Tournament_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTournamentStatus(arg0: string, arg1: TournamentStatus): Promise<Tournament> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournamentStatus(arg0, to_candid_TournamentStatus_n21(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Tournament_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournamentStatus(arg0, to_candid_TournamentStatus_n21(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Tournament_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_MatchResult_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchResult): MatchResult {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerStatus): PlayerStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Round_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Round): Round {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentStatus): TournamentStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Tournament_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tournament): Tournament {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Round]): Round | null {
    return value.length === 0 ? null : from_candid_Round_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: boolean;
    matches: Array<_Match>;
    roundNumber: bigint;
    tournamentId: string;
}): {
    completed: boolean;
    matches: Array<Match>;
    roundNumber: bigint;
    tournamentId: string;
} {
    return {
        completed: value.completed,
        matches: from_candid_vec_n14(_uploadFile, _downloadFile, value.matches),
        roundNumber: value.roundNumber,
        tournamentId: value.tournamentId
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    player1Id: string;
    player2Id: string;
    result: _MatchResult;
    winnerId: [] | [string];
    loserId: [] | [string];
    player2Name: string;
    byePlayerId: [] | [string];
    roundNumber: bigint;
    tournamentId: string;
    player1Name: string;
}): {
    id: string;
    player1Id: string;
    player2Id: string;
    result: MatchResult;
    winnerId?: string;
    loserId?: string;
    player2Name: string;
    byePlayerId?: string;
    roundNumber: bigint;
    tournamentId: string;
    player1Name: string;
} {
    return {
        id: value.id,
        player1Id: value.player1Id,
        player2Id: value.player2Id,
        result: from_candid_MatchResult_n17(_uploadFile, _downloadFile, value.result),
        winnerId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.winnerId)),
        loserId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.loserId)),
        player2Name: value.player2Name,
        byePlayerId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.byePlayerId)),
        roundNumber: value.roundNumber,
        tournamentId: value.tournamentId,
        player1Name: value.player1Name
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PlayerStatus;
    name: string;
    losses: bigint;
    eliminated: boolean;
    tournamentId: string;
}): {
    id: string;
    status: PlayerStatus;
    name: string;
    losses: bigint;
    eliminated: boolean;
    tournamentId: string;
} {
    return {
        id: value.id,
        status: from_candid_PlayerStatus_n3(_uploadFile, _downloadFile, value.status),
        name: value.name,
        losses: value.losses,
        eliminated: value.eliminated,
        tournamentId: value.tournamentId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TournamentStatus;
    name: string;
    createdAt: bigint;
    winner: [] | [string];
}): {
    id: string;
    status: TournamentStatus;
    name: string;
    createdAt: bigint;
    winner?: string;
} {
    return {
        id: value.id,
        status: from_candid_TournamentStatus_n7(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        winner: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.winner))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): MatchResult {
    return "pending" in value ? MatchResult.pending : "completed" in value ? MatchResult.completed : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    oneLoss: null;
} | {
    eliminated: null;
}): PlayerStatus {
    return "active" in value ? PlayerStatus.active : "oneLoss" in value ? PlayerStatus.oneLoss : "eliminated" in value ? PlayerStatus.eliminated : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    registration: null;
} | {
    completed: null;
}): TournamentStatus {
    return "active" in value ? TournamentStatus.active : "registration" in value ? TournamentStatus.registration : "completed" in value ? TournamentStatus.completed : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tournament>): Array<Tournament> {
    return value.map((x)=>from_candid_Tournament_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Round>): Array<Round> {
    return value.map((x)=>from_candid_Round_n12(_uploadFile, _downloadFile, x));
}
function to_candid_TournamentStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): _TournamentStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): {
    active: null;
} | {
    registration: null;
} | {
    completed: null;
} {
    return value == TournamentStatus.active ? {
        active: null
    } : value == TournamentStatus.registration ? {
        registration: null
    } : value == TournamentStatus.completed ? {
        completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
